In [280]:
import pandas as pd
import numpy as np

In [281]:
destinations=pd.read_csv("../../Datasets/destinations_of_nepal_updated_with_latlong.csv")
destinations

,title,avg_rating,voted_by,genre,history,art_and_architecture,nature,adventure,entertainment,health_and_lifestyle,food,industries,religious,latitude,longitude
0,Boudhanath Stupa,4.5,8897,['Religious Sites'],True,True,False,False,False,False,False,False,True,27.7215062,85.359809
1,Phewa Tal (Fewa Lake),4.5,2988,['Bodies of Water'],False,False,True,False,False,False,False,False,False,28.2116268,83.932296
2,Sarangkot,4.5,2199,['Mountains'],False,False,True,False,False,False,False,False,False,28.2443761,83.944564
3,Swayambhunath Temple,4.5,6203,['Religious Sites'],True,True,False,False,False,False,False,False,True,27.7149298,85.288146
4,Poon Hill,4.5,1477,['Mountains'],False,False,True,False,False,False,False,False,False,28.400195,83.671789
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3308,SITA (Travel Corporation India Ltd),4.77190569744597,0,"['Multi-day Tours', 'Balloon Rides']",True,False,False,False,False,False,False,False,False,NaN,NaN
3309,Himalayan Hike,4.77190569744597,0,"['City Tours', 'Multi-day Tours']",True,True,False,False,True,False,False,False,False,NaN,NaN
3310,Harilo,4.77190569744597,0,['Farmers Markets'],False,False,False,False,True,False,True,False,False,NaN,NaN
3311,Heli Sight,4.77190569744597,0,"['Parasailing & Paragliding', 'Multi-day Tours']",False,False,False,True,False,False,False,False,False,NaN,NaN
3312,River Fun,4.77190569744597,0,"['River Rafting & Tubing', 'Taxis & Shuttles']",False,False,False,True,False,False,False,False,False,NaN,NaN

In [282]:
# C = destinations['voted_by'].mean()
# m = destinations['avg_rating'].mean()
# C
# m
# def bayesian_avg(ratings):
#     bayesian_avg = (C*m+ratings.sum())/(C+ratings.count())
#     return bayesian_avg

In [283]:
destination_id_list=[i for i in range(len(destinations))]
destinations['id']=destination_id_list
destinations.set_index('id')

,title,avg_rating,voted_by,genre,history,art_and_architecture,nature,adventure,entertainment,health_and_lifestyle,food,industries,religious,latitude,longitude
id,,,,,,,,,,,,,,,
0,Boudhanath Stupa,4.5,8897,['Religious Sites'],True,True,False,False,False,False,False,False,True,27.7215062,85.359809
1,Phewa Tal (Fewa Lake),4.5,2988,['Bodies of Water'],False,False,True,False,False,False,False,False,False,28.2116268,83.932296
2,Sarangkot,4.5,2199,['Mountains'],False,False,True,False,False,False,False,False,False,28.2443761,83.944564
3,Swayambhunath Temple,4.5,6203,['Religious Sites'],True,True,False,False,False,False,False,False,True,27.7149298,85.288146
4,Poon Hill,4.5,1477,['Mountains'],False,False,True,False,False,False,False,False,False,28.400195,83.671789
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3308,SITA (Travel Corporation India Ltd),4.77190569744597,0,"['Multi-day Tours', 'Balloon Rides']",True,False,False,False,False,False,False,False,False,NaN,NaN
3309,Himalayan Hike,4.77190569744597,0,"['City Tours', 'Multi-day Tours']",True,True,False,False,True,False,False,False,False,NaN,NaN
3310,Harilo,4.77190569744597,0,['Farmers Markets'],False,False,False,False,True,False,True,False,False,NaN,NaN
3311,Heli Sight,4.77190569744597,0,"['Parasailing & Paragliding', 'Multi-day Tours']",False,False,False,True,False,False,False,False,False,NaN,NaN
3312,River Fun,4.77190569744597,0,"['River Rafting & Tubing', 'Taxis & Shuttles']",False,False,False,True,False,False,False,False,False,NaN,NaN

In [284]:
faulty_id_list=list(destinations[destinations['avg_rating']=='N']['id'])

In [285]:
faulty_id_list

[]

In [286]:
for i in faulty_id_list:
    destinations.drop(i,inplace=True)

In [287]:
destinations

,title,avg_rating,voted_by,genre,history,art_and_architecture,nature,adventure,entertainment,health_and_lifestyle,food,industries,religious,latitude,longitude,id
0,Boudhanath Stupa,4.5,8897,['Religious Sites'],True,True,False,False,False,False,False,False,True,27.7215062,85.359809,0
1,Phewa Tal (Fewa Lake),4.5,2988,['Bodies of Water'],False,False,True,False,False,False,False,False,False,28.2116268,83.932296,1
2,Sarangkot,4.5,2199,['Mountains'],False,False,True,False,False,False,False,False,False,28.2443761,83.944564,2
3,Swayambhunath Temple,4.5,6203,['Religious Sites'],True,True,False,False,False,False,False,False,True,27.7149298,85.288146,3
4,Poon Hill,4.5,1477,['Mountains'],False,False,True,False,False,False,False,False,False,28.400195,83.671789,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3308,SITA (Travel Corporation India Ltd),4.77190569744597,0,"['Multi-day Tours', 'Balloon Rides']",True,False,False,False,False,False,False,False,False,NaN,NaN,3308
3309,Himalayan Hike,4.77190569744597,0,"['City Tours', 'Multi-day Tours']",True,True,False,False,True,False,False,False,False,NaN,NaN,3309
3310,Harilo,4.77190569744597,0,['Farmers Markets'],False,False,False,False,True,False,True,False,False,NaN,NaN,3310
3311,Heli Sight,4.77190569744597,0,"['Parasailing & Paragliding', 'Multi-day Tours']",False,False,False,True,False,False,False,False,False,NaN,NaN,3311
3312,River Fun,4.77190569744597,0,"['River Rafting & Tubing', 'Taxis & Shuttles']",False,False,False,True,False,False,False,False,False,NaN,NaN,3312

In [288]:
destinations=destinations[:1000]
destinations.reset_index(inplace=True,drop=True)
destinations['voted_by']=pd.to_numeric(destinations['voted_by'])
destinations['avg_rating']=pd.to_numeric(destinations['avg_rating'])

/tmp/ipykernel_10778/1499022841.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  destinations['voted_by']=pd.to_numeric(destinations['voted_by'])
/tmp/ipykernel_10778/1499022841.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  destinations['avg_rating']=pd.to_numeric(destinations['avg_rating'])

In [289]:
# destinations.to_csv('only_rated_')

In [290]:
C = destinations['voted_by'].mean()
m = destinations['avg_rating'].mean()
C,m

(155.394, 4.630043811394892)

In [291]:
def bayesian_avg(avg_votes,voted_by):
    bayesian_avg = (C*m+avg_votes*voted_by)/(C+voted_by)
    return bayesian_avg

In [292]:
bayesian_avg_list=[]
for i in range(len(destinations)):
#     print(destinations.loc[i]['avg_rating'])
#     print(destinations.loc[i]['voted_by'])
    bayesian_avg_list.append(bayesian_avg(destinations.loc[i]['avg_rating'],destinations.loc[i]['voted_by']))
bayesian_avg_list

[4.5022323407518385,
 4.506428728955994,
 4.508583112269186,
 4.503178165434211,
 4.512379381465442,
 4.507874094167886,
 4.503968276615654,
 4.517689193069902,
 4.536450661493267,
 4.90094836960392,
 4.528566863767431,
 4.539905741434334,
 4.529656891648441,
 4.088092096977218,
 4.5113058609505785,
 4.535741497129255,
 4.521443290203353,
 4.016757690088669,
 4.585124426177148,
 4.792753368954981,
 4.733098545121488,
 4.504838630653118,
 4.571056449952875,
 4.82599874098167,
 4.020118598705303,
 4.528446225654916,
 4.154085540669094,
 4.6095915703759225,
 3.156900377496384,
 4.5434213333818185,
 4.569828773325978,
 4.180173185622031,
 4.533601978117337,
 4.681314389768495,
 4.9169707248010495,
 4.259423912483765,
 4.733098545121488,
 4.550723725828949,
 4.639327879518036,
 4.59559414187677,
 4.569588311149328,
 4.59338534353031,
 4.575573977082126,
 4.551763162415145,
 4.538316757543503,
 4.5750129105618464,
 4.616543986688685,
 4.590865886795048,
 4.599844995542841,
 4.527146951786148,
 3.7485328582300452,
 4.530975189882032,
 4.0603088517192365,
 4.159181618309339,
 4.312402368992061,
 3.9969015547176747,
 4.55190721235159,
 4.585847676779774,
 4.722803109192637,
 4.562294703440563,
 4.648157386610879,
 4.60900044245174,
 4.5921083895999795,
 4.104110647269015,
 4.6084156573060175,
 4.621446855222531,
 4.493487847555359,
 4.617903940790797,
 4.616543986688685,
 4.623676683525086,
 4.6095915703759225,
 4.596048499614523,
 4.495987861981103,
 4.215938075995488,
 4.582349315907878,
 4.621446855222531,
 4.614561878680101,
 4.543608739059845,
 4.536648452884387,
 4.221472296062754,
 4.650297626603756,
 4.620004442129161,
 4.666525679709839,
 4.533850769533888,
 4.60726471133846,
 4.599195980439293,
 4.621446855222531,
 4.6684488968931905,
 4.756808667004653,
 4.699630228888564,
 4.501064659241829,
 4.641576542937378,
 4.567271743203586,
 4.460959481095972,
 4.759856253823814,
 4.6142328320256585,
 4.570807473275185,
 4.593818899448907,
 4.6684488968931905,
 4.688227534669772,
 4.620004442129161,
 4.57458025533703,
 4.45243873687763,
 4.677741560971209,
 4.6185958896903525,
 4.620721340238586,
 4.730597055343158,
 4.273177084515639,
 4.617903940790797,
 4.574460113443547,
 4.581404492012173,
 4.710228273173069,
 4.62292436480588,
 4.332564617580175,
 4.555338702284324,
 4.626015243729925,
 4.410685789188897,
 4.650297626603756,
 4.643797340842274,
 4.582015097883463,
 4.608640655756518,
 4.603953969916241,
 4.547841655013798,
 4.5747152773535005,
 4.632409350920738,
 4.621446855222531,
 4.581404492012173,
 4.622037866932017,
 4.616543986688685,
 4.620004442129161,
 4.632409350920738,
 4.619296008287766,
 4.58336851583743,
 4.602977419900999,
 4.626015243729925,
 4.600340765007388,
 4.617903940790797,
 4.62292436480588,
 4.613916073981633,
 4.430552380572477,
 4.634744831619362,
 4.622181143378223,
 4.675924935611677,
 4.591690463569325,
 4.609330902244672,
 4.6126460641264355,
 4.60289534317697,
 4.626015243729925,
 4.6185958896903525,
 4.615875706893,
 4.389601649634224,
 4.564895367373482,
 4.533850769533888,
 4.5921083895999795,
 4.662611524043674,
 4.64599078800878,
 4.648157386610879,
 4.6050346062138,
 4.6185958896903525,
 4.571227861114729,
 4.594698201579697,
 4.623676683525086,
 4.654500931691635,
 4.628391349275689,
 4.618110711440445,
 4.548813458008105,
 4.600841482419123,
 4.555456533389402,
 4.625209289241842,
 4.623676683525086,
 4.395745361762605,
 4.516938382567019,
 4.621446855222531,
 4.558677061818434,
 3.3043018426705357,
 4.398970749194756,
 4.6142328320256585,
 4.503642231899636,
 4.613277509489657,
 4.397351510296103,
 4.5686427985213625,
 4.57458025533703,
 4.628391349275689,
 4.656564918861475,
 4.625989924984088,
 4.594256499845601,
 4.628391349275689,
 4.6185958896903525,
 4.627580767124372,
 4.625209289241842,
 4.625989924984088,
 4.350809752356647,
 4.550979651629182,
 3.7760529544902726,
 4.627580767124372,
 4.5646390764841795,
 4.45243873687763,
 4.581354734928774,
 4.581333226768833,
 4.577972230586076,
 4.634744831619362,
 4.622181143378223,
 4.662611524043674,
 4.588392778753428,
 4.672229540508215,
 4.627580767124372,
 4.6370508228083,
 4.626780355771848,
 4.588392778753428,
 4.495510210256006,
 4.501064659241829,
 4.5951440625813245,
 4.558200554339931,
 4.581333226768833,
 4.619621136539112,
 4.626015243729925,
 4.55190721235159,
 4.5550360444680535,
 4.621446855222531,
 4.641576542937378,
 4.628391349275689,
 4.622181143378223,
 4.403330493883031,
 4.622037866932017,
 4.634744831619362,
 4.632409350920738,
 4.581404492012173,
 4.561401355711193,
 4.617220019420037,
 4.5127341662796745,
 4.6142328320256585,
 4.626015243729925,
 4.628391349275689,
 4.626015243729925,
 4.371932768741362,
 4.191447353758351,
 4.6244382675954645,
 4.648157386610879,
 4.6142328320256585,
 4.656564918861475,
 4.628391349275689,
 4.596507197092074,
 4.626015243729925,
 4.5646390764841795,
 4.56171945794828,
 4.5646390764841795,
 4.548813458008105,
 4.602885747182149,
 4.488562671676287,
 4.431199622086525,
 4.627580767124372,
 4.626015243729925,
 4.489230549346117,
 4.5127341662796745,
 4.588033186040979,
 4.621446855222531,
 4.626780355771848,
 4.6370508228083,
 4.5747152773535005,
 4.662611524043674,
 4.613916073981633,
 4.531488615233308,
 4.421288966272356,
 4.62292436480588,
 4.600340765007388,
 4.641576542937378,
 4.591950300663251,
 4.628391349275689,
 4.588033186040979,
 4.533850769533888,
 4.617903940790797,
 4.630043811394892,
 4.64599078800878,
 4.6142328320256585,
 4.639327879518036,
 4.628391349275689,
 4.236604226733466,
 4.567914359130236,
 4.626780355771848,
 4.610403307030798,
 4.619621136539112,
 4.394131327983023,
 4.610793271861453,
 4.392571705926758,
 4.622037866932017,
 4.639327879518036,
 4.589700544388663,
 4.366145194087743,
 4.6185958896903525,
 4.531488615233308,
 4.6524119860931945,
 4.427178411290209,
 4.627580767124372,
 4.634744831619362,
 4.619621136539112,
 4.62292436480588,
 4.5490341829928065,
 4.478862325539861,
 4.592530142897231,
 4.628391349275689,
 4.626780355771848,
 4.632409350920738,
 4.639327879518036,
 4.608640655756518,
 4.6370508228083,
 4.576590260787093,
 4.626015243729925,
 4.606621237641411,
 4.6370508228083,
 4.504204591778198,
 4.632409350920738,
 4.45243873687763,
 4.531488615233308,
 4.591690463569325,
 4.622181143378223,
 4.588033186040979,
 4.428667250575312,
 4.64599078800878,
 4.622037866932017,
 4.555338702284324,
 4.625209289241842,
 4.555338702284324,
 4.608640655756518,
 4.568177841210129,
 4.620721340238586,
 4.634744831619362,
 4.610403307030798,
 4.6370508228083,
 4.539736860248397,
 4.6370508228083,
 4.427889489091502,
 4.625209289241842,
 4.568177841210129,
 4.522284625815221,
 4.602885747182149,
 4.639327879518036,
 4.599195980439293,
 4.634744831619362,
 4.618110711440445,
 4.626015243729925,
 4.626015243729925,
 4.625209289241842,
 4.606621237641411,
 4.6370508228083,
 4.594816689077509,
 4.648157386610879,
 4.606621237641411,
 4.608640655756518,
 4.639327879518036,
 4.632409350920738,
 4.634744831619362,
 4.608640655756518,
 4.622037866932017,
 4.627580767124372,
 4.608640655756518,
 4.60726471133846,
 4.581333226768833,
 4.634744831619362,
 4.568177841210129,
 4.632409350920738,
 4.619621136539112,
 4.641576542937378,
 4.615684384588344,
 4.626015243729925,
 4.613916073981633,
 4.608640655756518,
 4.5694451344405485,
 4.60168530827947,
 4.628391349275689,
 4.632409350920738,
 4.626015243729925,
 4.608640655756518,
 4.632409350920738,
 4.625209289241842,
 4.632409350920738,
 4.632409350920738,
 4.632409350920738,
 4.615684384588344,
 4.594816689077509,
 4.618110711440445,
 4.626015243729925,
 4.632409350920738,
 4.626015243729925,
 4.606832922157486,
 4.608640655756518,
 4.615684384588344,
 4.626015243729925,
 4.602977419900999,
 4.619621136539112,
 4.622037866932017,
 4.627580767124372,
 4.658604392246148,
 4.460959481095972,
 4.632409350920738,
 4.626780355771848,
 4.626015243729925,
 4.616543986688685,
 4.626015243729925,
 4.619621136539112,
 4.609330902244672,
 4.619621136539112,
 4.615684384588344,
 4.619621136539112,
 4.619621136539112,
 4.619621136539112,
 4.619621136539112,
 4.619621136539112,
 4.5612903773368805,
 4.619621136539112,
 4.619621136539112,
 4.626015243729925,
 4.606621237641411,
 4.615684384588344,
 4.623676683525086,
 4.609330902244672,
 4.588392778753428,
 4.622037866932017,
 4.5550360444680535,
 4.618110711440445,
 4.630043811394892,
 4.594816689077509,
 4.550857082840117,
 4.618110711440445,
 4.608640655756518,
 4.627580767124372,
 4.626015243729925,
 4.632409350920738,
 4.56171945794828,
 4.622037866932017,
 4.619621136539112,
 4.626015243729925,
 4.615684384588344,
 4.626015243729925,
 4.626015243729925,
 4.626015243729925,
 4.626015243729925,
 4.615684384588344,
 4.602977419900999,
 4.619621136539112,
 4.619621136539112,
 4.942302972546902,
 4.960607641272952,
 4.9622129626039655,
 4.851600768282157,
 4.900605863871164,
 4.9376741696367255,
 4.93753873670178,
 4.917801736972147,
 4.8720744558848095,
 4.842665801923124,
 4.93093538399832,
 4.832585974210085,
 4.832097022809681,
 4.811136316839025,
 4.779223131208469,
 4.803385254238794,
 4.8903706526541075,
 4.801347049447805,
 4.8595754408415806,
 4.814787102933362,
 4.80925641528331,
 4.801347049447805,
 4.801347049447805,
 4.772225282803466,
 4.849266186746247,
 4.7704059523307185,
 4.815381889271785,
 4.775778793684322,
 4.793497805369002,
 4.889739866641921,
 4.799964606177923,
 4.9226668873139925,
 4.816560074627779,
 4.777514292235493,
 4.857132631271584,
 4.925858373972326,
 4.833555383208446,
 4.859917610949229,
 4.828080133100169,
 4.858886061227946,
 4.84352228949819,
 4.833072086121994,
 4.858538826921406,
 4.8642187372232435,
 4.938342619137294,
 4.790487503472736,
 4.806690881550731,
 4.919074524880416,
 4.897413298550481,
 4.809887193621229,
 4.815972867685993,
 4.841799886701206,
 4.8720744558848095,
 4.807982217505688,
 4.8135859583127365,
 4.920197875090434,
 4.80538205931027,
 4.84886992967265,
 4.779223131208469,
 4.854603327384578,
 4.840924387311073,
 4.858189879544093,
 4.861269777139384,
 4.787388137413914,
 4.8177233175897385,
 4.824404320262125,
 4.828080133100169,
 4.79714118163369,
 4.91732892148609,
 4.806038678339973,
 4.9345521804883665,
 4.833555383208446,
 4.806690881550731,
 4.916000181222947,
 4.792753368954981,
 4.828080133100169,
 4.823325039883643,
 4.875939325990189,
 4.8456232593111,
 4.841363344944723,
 4.87034336961686,
 4.794970748403667,
 4.763802838311125,
 4.782563250406204,
 4.877785490520496,
 4.829608789806274,
 4.7704059523307185,
 4.882530288536226,
 4.87264125803156,
 4.806038678339973,
 4.887583796501128,
 4.77131923605137,
 4.76184589520824,
 4.894976978242177,
 4.8553350781035896,
 4.891610817671199,
 4.865174059737937,
 4.8188719006279195,
 4.880329537895765,
 4.854970125753412,
 4.852362974334216,
 4.909379704139538,
 4.832585974210085,
 4.869460138030713,
 4.847668558662559,
 4.925280191979529,
 4.776649914247799,
 4.80925641528331,
 4.921505402867716,
 4.864857116056874,
 4.829608789806274,
 4.87647246854901,
 4.859917610949229,
 4.821126181658332,
 4.864538678746396,
 4.799964606177923,
 4.764769298869441,
 4.773124178267433,
 4.895549421010945,
 4.790487503472736,
 4.917919097005254,
 4.862596088920725,
 4.914117885771157,
 4.780067744584413,
 4.83011231885878,
 4.840039143747247,
 4.8238663334126795,
 4.860258117590188,
 4.910368709448323,
 4.777514292235493,
 4.802031130215838,
 4.924692921385153,
 4.812369132645868,
 4.8456232593111,
 4.867657076359015,
 4.757833087727145,
 4.788171544057341,
 4.832585974210085,
 4.872922779762548,
 4.882530288536226,
 4.796422827779265,
 4.821681011519749,
 4.831605206968775,
 4.877001048425735,
 4.916488272744821,
 4.822780409094798,
 4.902295108427173,
 4.875939325990189,
 4.8564189973573475,
 4.812369132645868,
 4.920965842484126,
 4.869460138030713,
 4.904407140789396,
 4.894976978242177,
 4.769485344586871,
 4.774900851343015,
 4.824404320262125,
 4.808621437272042,
 4.860258117590188,
 4.8382387660677955,
 4.80538205931027,
 4.776649914247799,
 4.8748591144592615,
 4.891200558726817,
 4.834513630137245,
 4.847668558662559,
 4.884882533686624,
 4.786598914704477,
 4.899034812498723,
 4.884186811339174,
 4.897045863723282,
 4.885797264226229,
 4.7704059523307185,
 4.9376065266627505,
 4.887583796501128,
 4.876206471289246,
 4.882769830030338,
 4.96591011829258,
 4.896861157507791,
 4.756808667004653,
 4.880079909276916,
 4.844789678093862,
 4.873203059652086,
 4.789721164428985,
 4.777514292235493,
 4.777514292235493,
 4.794970748403667,
 4.550219506324393,
 4.780067744584413,
 4.80271051575495,
 4.776649914247799,
 4.9047239913355085,
 4.783382548316458,
 4.758848914099759,
 4.834513630137245,
 4.532784271144589,
 4.779223131208469,
 4.765727882621001,
 4.772225282803466,
 4.7704059523307185,
 4.749387638856718,
 4.780905920211201,
 4.795699368244874,
 4.757833087727145,
 4.744940096133428,
 4.787388137413914,
 4.7628284034584105,
 4.774016006776488,
 4.822780409094798,
 4.756808667004653,
 4.5497252125471785,
 4.791248277115326,
 4.825470494386352,
 4.5360603932731225,
 4.746066715672226,
 4.7704059523307185,
 4.789721164428985,
 4.749387638856718,
 4.789721164428985,
 4.807982217505688,
 4.809887193621229,
 4.836861660606872,
 4.785803810919387,
 4.783382548316458,
 4.749387638856718,
 4.775778793684322,
 4.780067744584413,
 4.769485344586871,
 4.77837200562811,
 4.773124178267433,
 4.783382548316458,
 4.804055393184243,
 4.756808667004653,
 4.83639740014883,
 4.80538205931027,
 4.8349886278980065,
 4.77131923605137,
 4.753682734037285,
 4.749387638856718,
 4.789721164428985,
 4.80472097946255,
 4.757833087727145,
 4.735554008058631,
 4.741499447052969,
 4.774016006776488,
 4.746066715672226,
 4.747183426246506,
 4.763802838311125,
 4.5715596932934055,
 4.7557755424008175,
 4.780905920211201,
 4.752622821707522,
 4.747183426246506,
 4.751553748273067,
 4.76184589520824,
 4.73796470289934,
 4.759856253823814,
 4.8456232593111,
 4.751553748273067,
 4.776649914247799,
 4.777514292235493,
 4.777514292235493,
 4.807982217505688,
 4.759856253823814,
 4.756808667004653,
 4.73796470289934,
 4.744940096133428,
 4.77131923605137,
 4.819440781006859,
 4.756808667004653,
 4.760855212808547,
 4.812979524739903,
 4.739153643147717,
 4.743803435153783,
 4.886473828733946,
 4.741499447052969,
 4.828080133100169,
 4.73676487462063,
 4.730597055343158,
 4.780067744584413,
 4.735554008058631,
 4.7482903580124605,
 4.794236912846725,
 4.740331842904045,
 4.73796470289934,
 4.796422827779265,
 4.795699368244874,
 4.754733602514987,
 4.807982217505688,
 4.788949198689758,
 4.747183426246506,
 4.740331842904045,
 4.742656597884894,
 4.767621801773276,
 4.744940096133428,
 4.82056788837462,
 4.743803435153783,
 4.747183426246506,
 4.73796470289934,
 4.834035889847682,
 4.7482903580124605,
 4.833555383208446,
 4.569112321141672,
 4.839143992422643,
 4.806690881550731,
 4.8567767032588876,
 4.7628284034584105,
 4.821681011519749,
 4.731853634093762,
 4.739153643147717,
 4.725450719829116,
 4.8188719006279195,
 4.730597055343158,
 4.7241332669265805,
 4.743803435153783,
 4.744940096133428,
 4.766678685470823,
 4.858189879544093,
 4.749387638856718,
 4.767621801773276,
 4.728048232342913,
 4.741499447052969,
 4.787388137413914,
 4.77837200562811,
 4.80472097946255,
 4.821126181658332,
 4.765727882621001,
 4.731853634093762,
 4.726755649057948,
 4.726755649057948,
 4.725450719829116,
 4.752622821707522,
 4.735554008058631,
 4.76184589520824,
 4.704265707932847,
 4.714544763140401,
 4.763802838311125,
 4.757833087727145,
 4.757833087727145,
 4.161721173364615,
 4.740331842904045,
 4.715955156911262,
 4.741499447052969,
 4.754733602514987,
 4.744940096133428,
 4.746066715672226,
 4.728048232342913,
 4.721460061958671,
 4.759856253823814,
 4.733098545121488,
 4.729328644066677,
 4.721460061958671,
 4.742656597884894,
 4.726755649057948,
 4.754733602514987,
 4.759856253823814,
 4.792753368954981,
 4.742656597884894,
 4.752622821707522,
 4.170746516405644,
 4.715955156911262,
 4.733098545121488,
 4.176598282138512,
 4.585847676779774,
 4.720103936959687,
 4.722803109192637,
 4.720103936959687,
 4.718734542246337,
 4.721460061958671,
 4.780905920211201,
 4.733098545121488,
 4.746066715672226,
 4.77837200562811,
 4.707277350773944,
 4.782563250406204,
 4.717351682094348,
 4.722803109192637,
 4.751553748273067,
 4.731853634093762,
 4.743803435153783,
 4.751553748273067,
 4.743803435153783,
 4.787388137413914,
 4.735554008058631,
 4.7116815351911185,
 4.857486794617416,
 4.718734542246337,
 4.717351682094348,
 4.781737731413388,
 4.7241332669265805,
 4.774016006776488,
 4.758848914099759,
 4.7241332669265805,
 4.8135859583127365,
 4.7131202931619605,
 4.73433195018299,
 4.707277350773944,
 4.73433195018299,
 4.699630228888564,
 4.726755649057948,
 4.747183426246506,
 4.717351682094348,
 4.746066715672226,
 4.715955156911262,
 4.704265707932847,
 4.73433195018299,
 4.760855212808547,
 4.705779235943263,
 4.710228273173069,
 4.720103936959687,
 4.714544763140401,
 4.773124178267433,
 4.742656597884894,
 4.705779235943263,
 4.717351682094348,
 4.751553748273067,
 4.7131202931619605,
 4.708760286674862,
 4.704265707932847,
 4.812979524739903,
 4.731853634093762,
 4.728048232342913,
 4.751553748273067,
 4.7027365276476925,
 4.704265707932847,
 4.764769298869441,
 4.77131923605137,
 4.731853634093762,
 4.7557755424008175,
 4.742656597884894,
 4.721460061958671,
 4.783382548316458,
 4.73796470289934,
 4.568179612366977,
 4.73796470289934,
 4.7131202931619605,
 4.705779235943263,
 4.7027365276476925,
 4.740331842904045,
 4.721460061958671,
 4.754733602514987,
 4.7027365276476925,
 4.7131202931619605,
 4.84603670125363,
 4.726755649057948,
 4.7027365276476925,
 4.701191451021851,
 4.725450719829116,
 4.7027365276476925,
 4.720103936959687,
 4.698052606846318,
 4.714544763140401,
 4.73796470289934,
 4.7116815351911185,
 4.708760286674862,
 4.763802838311125,
 4.751553748273067,
 4.698052606846318,
 4.694847118421488,
 4.807338713338398,
 4.701191451021851,
 4.572849549838489,
 4.752622821707522,
 4.7131202931619605,
 4.7241332669265805,
 4.802031130215838,
 4.747183426246506,
 4.7241332669265805,
 4.710228273173069,
 4.741499447052969,
 4.717351682094348,
 4.730597055343158,
 4.717351682094348,
 4.731853634093762,
 4.698052606846318,
 4.705779235943263,
 4.731853634093762,
 4.694847118421488,
 4.705779235943263,
 4.744940096133428,
 4.722803109192637,
 4.7027365276476925,
 4.7131202931619605,
 4.599844995542841,
 4.693218715796118,
 4.696458325120637,
 4.588093097587112,
 4.7131202931619605,
 4.756808667004653,
 4.587331685471092,
 4.8359304897569535,
 4.710228273173069,
 4.757833087727145,
 4.7027365276476925,
 4.741499447052969,
 4.699630228888564,
 4.594256499845601,
 4.750475394445593,
 4.699630228888564,
 4.812369132645868,
 4.704265707932847,
 4.694847118421488,
 4.698052606846318,
 4.73433195018299,
 4.721460061958671,
 4.701191451021851,
 4.701191451021851,
 4.722803109192637,
 4.8578392063875775,
 4.785002760076509,
 4.699630228888564,
 4.729328644066677,
 4.698052606846318,
 4.718734542246337,
 4.694847118421488,
 4.842234032470068,
 4.728048232342913,
 4.69157284047715,
 4.693218715796118,
 4.699630228888564,
 4.693218715796118,
 4.844789678093862,
 4.689909209725761,
 4.730597055343158,
 4.694847118421488,
 4.718734542246337,
 4.69157284047715,
 4.708760286674862,
 4.725450719829116,
 4.728048232342913,
 4.729328644066677,
 4.714544763140401,
 4.7027365276476925,
 4.586583322741364,
 4.679537933419724,
 4.699630228888564,
 4.720103936959687,
 4.689909209725761,
 4.850830651302039,
 4.754733602514987,
 4.705779235943263,
 4.707277350773944,
 4.693218715796118,
 4.693218715796118,
 4.707277350773944,
 4.708760286674862,
 4.720103936959687,
 4.701191451021851,
 4.698052606846318,
 4.704265707932847,
 4.7027365276476925,
 4.684808864479631,
 4.705779235943263,
 4.69157284047715,
 4.696458325120637,
 4.754733602514987,
 4.689909209725761,
 4.73676487462063,
 4.704265707932847,

In [293]:
destinations['bayesian_avg']=bayesian_avg_list

/tmp/ipykernel_10778/1024126132.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  destinations['bayesian_avg']=bayesian_avg_list

In [294]:
destinations

,title,avg_rating,voted_by,genre,history,art_and_architecture,nature,adventure,entertainment,health_and_lifestyle,food,industries,religious,latitude,longitude,id,bayesian_avg
0,Boudhanath Stupa,4.5,8897,['Religious Sites'],True,True,False,False,False,False,False,False,True,27.7215062,85.359809,0,4.502232
1,Phewa Tal (Fewa Lake),4.5,2988,['Bodies of Water'],False,False,True,False,False,False,False,False,False,28.2116268,83.932296,1,4.506429
2,Sarangkot,4.5,2199,['Mountains'],False,False,True,False,False,False,False,False,False,28.2443761,83.944564,2,4.508583
3,Swayambhunath Temple,4.5,6203,['Religious Sites'],True,True,False,False,False,False,False,False,True,27.7149298,85.288146,3,4.503178
4,Poon Hill,4.5,1477,['Mountains'],False,False,True,False,False,False,False,False,False,28.400195,83.671789,4,4.512379
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,Eagle Treks and Expedition P Ltd & Heli Tour P...,5.0,79,"['City Tours', 'Helicopter Tours']",True,True,False,False,True,False,False,False,False,NaN,NaN,995,4.754734
996,Hi Himalaya Nepal - Treks & Tours,5.0,30,"['Multi-day Tours', 'Walking Tours']",True,False,False,False,False,False,False,False,False,NaN,NaN,996,4.689909
997,Asian Hiking Team's Kathmandu Day Hiking,5.0,63,"['Climbing Tours', 'Hiking & Camping Tours']",False,False,True,True,False,False,False,False,False,NaN,NaN,997,4.736765
998,Annapurna Mountain Bike & Adventure,5.0,39,"['Bike Tours', 'Eco Tours']",False,False,False,True,False,False,False,False,False,NaN,NaN,998,4.704266
999,Tour Guide in Nepal,5.0,29,"['Multi-day Tours', '4WD, ATV & Off-Road Tours']",True,False,False,False,False,False,False,False,False,NaN,NaN,999,4.688228

In [295]:
destinations.drop('id',axis=1)

,title,avg_rating,voted_by,genre,history,art_and_architecture,nature,adventure,entertainment,health_and_lifestyle,food,industries,religious,latitude,longitude,bayesian_avg
0,Boudhanath Stupa,4.5,8897,['Religious Sites'],True,True,False,False,False,False,False,False,True,27.7215062,85.359809,4.502232
1,Phewa Tal (Fewa Lake),4.5,2988,['Bodies of Water'],False,False,True,False,False,False,False,False,False,28.2116268,83.932296,4.506429
2,Sarangkot,4.5,2199,['Mountains'],False,False,True,False,False,False,False,False,False,28.2443761,83.944564,4.508583
3,Swayambhunath Temple,4.5,6203,['Religious Sites'],True,True,False,False,False,False,False,False,True,27.7149298,85.288146,4.503178
4,Poon Hill,4.5,1477,['Mountains'],False,False,True,False,False,False,False,False,False,28.400195,83.671789,4.512379
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,Eagle Treks and Expedition P Ltd & Heli Tour P...,5.0,79,"['City Tours', 'Helicopter Tours']",True,True,False,False,True,False,False,False,False,NaN,NaN,4.754734
996,Hi Himalaya Nepal - Treks & Tours,5.0,30,"['Multi-day Tours', 'Walking Tours']",True,False,False,False,False,False,False,False,False,NaN,NaN,4.689909
997,Asian Hiking Team's Kathmandu Day Hiking,5.0,63,"['Climbing Tours', 'Hiking & Camping Tours']",False,False,True,True,False,False,False,False,False,NaN,NaN,4.736765
998,Annapurna Mountain Bike & Adventure,5.0,39,"['Bike Tours', 'Eco Tours']",False,False,False,True,False,False,False,False,False,NaN,NaN,4.704266
999,Tour Guide in Nepal,5.0,29,"['Multi-day Tours', '4WD, ATV & Off-Road Tours']",True,False,False,False,False,False,False,False,False,NaN,NaN,4.688228

In [296]:
destinations.to_csv("top_1000_destinations_of_nepal_bayesian_avg.csv",index=None)

In [299]:
destinations.sort_values('bayesian_avg',ascending=False)

,title,avg_rating,voted_by,genre,history,art_and_architecture,nature,adventure,entertainment,health_and_lifestyle,food,industries,religious,latitude,longitude,id,bayesian_avg
617,Himalayan Social Journey,5.0,1531,"['Historical & Heritage Tours', 'Sightseeing T...",True,True,False,False,False,False,False,False,False,NaN,NaN,617,4.965910
442,Ace the Himalaya,5.0,1366,"['Multi-day Tours', 'Cultural Tours']",True,False,False,False,False,False,False,False,False,NaN,NaN,442,4.962213
441,Nepal Eco Adventure,5.0,1304,"['Multi-day Tours', 'Historical & Heritage Tou...",True,False,False,False,False,False,False,False,False,NaN,NaN,441,4.960608
440,Nepal Hiking Team,5.0,841,"['City Tours', 'Cultural Tours']",True,True,False,False,True,False,False,False,False,NaN,NaN,440,4.942303
484,Flying Buddha Paragliding,5.0,777,['Parasailing & Paragliding'],False,False,False,True,False,False,False,False,False,NaN,NaN,484,4.938343
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55,Bat Cave,3.5,198,"['Nature & Wildlife Areas', 'Caverns & Caves']",False,False,True,True,False,False,False,False,False,28.2674636,83.973741,55,3.996902
193,Freak Street (Jhhonchen Tole),3.0,171,['Points of Interest & Landmarks'],True,True,True,False,False,False,False,False,False,NaN,NaN,193,3.776053
50,Mahendra Cave,3.0,183,['Caverns & Caves'],False,False,True,False,False,False,False,False,False,28.2716656,83.977323,50,3.748533
174,Elephant Breeding Centre,3.0,677,['Nature & Wildlife Areas'],False,False,True,True,False,False,False,False,False,NaN,NaN,174,3.304302
28,Devi's Fall,3.0,1459,['Waterfalls'],False,False,False,False,False,False,False,False,False,28.1901905,83.957025,28,3.156900